#!/bin/sh; C:/Program\ Files/Git/usr/bin/sh.exe
echo "running precommit hook"
LC_ALL=C

# Select files to format
GITFILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g') 

# remove root src dir from git file path when passing to dotnet format
[ -z "$GITFILES" ] && exit 0

# Format all selected files
echo "$DOTNETFORMATFILES" | cat | xargs | sed -e 's/ /,/g' | xargs dotnet-format -v diag -f 
echo "$DOTNETFORMATFILES" | cat | xargs | sed -e 's/ /,/g' | xargs dotnet-format -v diag -s info

# Add back the modified files to staging
echo "$GITFILES" |  git update-index --again
exit 0